spring.application.name=mi-extractor
# Permitir archivos de hasta 50MB (ajusta si tus libros son más pesados)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB